import "./globals.css";
import { Inter, Montez, Montserrat } from "next/font/google";
import Provider from "@/components/provider/Provider";

const inter = Inter({ subsets: ["latin"] });

const montserrat = Montserrat({ subsets: ["latin"] });
const montez = Montez({
  weight: "400",
  variable: "--montez",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} ${montez.variable}`}>
        {/* <body> */}
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
